name: Flowable Database Tests

on:
  push:
    branches:
      - main
      - 'flowable-release-*'
    paths-ignore:
      - 'docs/**'
      - 'ide-settings/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'pull_request_template.md'
      - '.github/pull_request_template.md'
  pull_request:
    branches:
      - main
      - 'flowable-release-*'
    paths-ignore:
      - 'docs/**'
      - 'ide-settings/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'pull_request_template.md'
      - '.github/pull_request_template.md'

jobs:
  postgres:
    uses: ./.github/workflows/postgres.yml
  mysql:
    uses: ./.github/workflows/mysql.yml
  mariadb:
    uses: ./.github/workflows/mariadb.yml
  oracle:
    uses: ./.github/workflows/oracle.yml
  sql-server:
    uses: ./.github/workflows/sql-server.yml
  db2:
    uses: ./.github/workflows/db2.yml
